- hosts: webservers
  user: vagrant
  sudo: yes
  vars:
    user_name: vagrant
    home: /home/{{user_name}}
    python_version: 2.7.11
    python_source_url: https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
    pip_source_url: https://raw.github.com/pypa/pip/master/contrib/get-pip.py
    venv_name: webdev
    mysql_root_password: root
  handlers:
    - include: handlers/python.yml
    - include: handlers/service.yml

  tasks:
    - include: tasks/basic.yml
    - include: tasks/mysql.yml
    - include: tasks/python.yml
    - include: tasks/django.yml
    - include: tasks/nginx.yml
    - include: tasks/supervisord.yml
