- name: update all yum packages
  yum: name=* state=latest

- name: install yum packages
  yum: name={{ item }} state=present
  with_items:
   - gcc
   - zlib
   - zlib-devel
   - libxml2-devel
   - gdbm-devel
   - readline-devel
   - bzip2-devel
   - db4-devel
   - openssl-devel
   - git
   - python-devel
   - libevent-devel
