  - name: copy requirements.txt
    copy: src=templates/requirements.txt dest=/home/vagrant/requirements.txt

  - name: Install python libraries
    pip: virtualenv={{ home }}/venvs/{{ venv_name }} requirements=/home/vagrant/requirements.txt
    sudo: no
    notify: pip freeze
