- name: add yum repo
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

- include_vars: vars/mysql.yml
- name: install mysql
  yum: name={{ item }} state=present
  with_items:
    - mysql-community-libs-compat
    - mysql-community-client
    - mysql-community-server
    - MySQL-python

- name: start mysql
  service: name=mysqld state=started enabled=yes

- shell: chkconfig mysqld on

- name: set db root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost


