#- name: add yum repo for latest version of Nginx
#  command: rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm

- name: install Nginx
  yum: name=nginx state=present

- name: Main config file
  template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf

- name: config file for webserver
  template: src=templates/django_nginx.conf dest=/etc/nginx/conf.d/web_server.conf
