  - file: path={{ home }}/downloads state=directory
    sudo: no

  - name: download python tar
    get_url: url={{ python_source_url }} dest={{ home }}/downloads/Python.tgz
    sudo: no

  - name: tar python
    command: tar zxvf {{ home }}/downloads/Python.tgz -C {{ home }}/downloads
    sudo: no

  - command: /home/vagrant/downloads/Python-{{ python_version }}/configure --prefix=/usr/local --with-threads
    sudo: no
  - command: make
  - command: make altinstall

  - name: install pip
    get_url: url={{ pip_source_url }} dest=/home/vagrant/downloads/get_pip.py
    sudo: no

  - command: /usr/local/bin/python2.7 {{ home }}/downloads/get_pip.py

  - command: /usr/local/bin/pip install virtualenv
  - shell: rm -rf /home/vagrant/*
  - file: path={{home}}/venvs state=directory
    sudo: no

  - command: virtualenv {{ home }}/venvs/{{ venv_name }}
    sudo: no


