- name: get easy_install_path
  shell: which easy_install
  register: easy_install_path

- name: Install Supervisor
  command: /usr/bin/easy_install supervisor

- name: Copy config file of Supervisord
  template: src=templates/supervisord.conf dest=/etc/supervisord.conf

- name: Copy starting script of Supervisord
  template: src=templates/supervisord.ini dest=/etc/init.d/supervisord

- name: add service supervisord
  command: chkconfig --add supervisord

- name: Create ini directory
  file: path=/etc/supervisord.d mode=0644 state=directory owner=root

- name: Create log directory
  file: path=/var/log/supervisord/jobs mode=0664 state=directory owner=root

- name: copy program ini files
  template: src=templates/django_supervisord.ini dest=/etc/supervisord.d/django_server.ini
